# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Replace the '❯' symbol in the prompt with '$'
[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[username]
style_user = 'bright-blue'
style_root = 'green bold'
format = '[$user]($style) '
disabled = false
show_always = true

[hostname]
ssh_only = false
format = 'on [$ssh_symbol](blue bold)[$hostname](yellow) '
disabled = false
